Traceback (most recent call last):
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\dudas\anaconda3\envs\wintest\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
aStr = '10'
aFlt = 10.0
print( "aVar=", aVar, "; aStr =", aStr, "; aFlt =", aFlt  )

# Is aVar equal to aStr?
print( "\n#-# Is aVar equal to aStr?")
print( aVar == aStr )
print( "aVar type is ", type( aVar ), "; and aStr type is ", type( aStr ) )

# Is aVar equal to aFlt?
print( "\n#-# Is aVar equal to aFlt?")
print( aVar == aFlt)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-7-d9e906cfebe7>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0maStr[0m [1;33m=[0m [1;34m'10'[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [0maFlt[0m [1;33m=[0m [1;36m10.0[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [0mprint[0m[1;33m([0m [1;34m"aVar="[0m[1;33m,[0m [0maVar[0m[1;33m,[0m [1;34m"; aStr ="[0m[1;33m,[0m [0maStr[0m[1;33m,[0m [1;34m"; aFlt ="[0m[1;33m,[0m [0maFlt[0m  [1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [1;31m# Is aVar equal to aStr?[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'aVar' is not defined
NameError: name 'aVar' is not defined

