Traceback (most recent call last):
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\pmd19\Anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# guessingGame
# A python number guessing game
#
# Adam Lavely
# adam.lavely.psu@gmail.com
#
# Created for ICS Python Training Series
# Spring 2019
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# This is a number guessing game.  Python
# uses a random number generator to get
# a target between minVal and maxVal
# and then the guesser must guess this
# number using greater/less than clues.
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Load the modules we need

# Use random to get the random number 
import random as rd 

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Functions required

def guessChecker( guessVal ):
    # Function to verify that the guess an integer
    if guessVal.isdigit() == True:
        return True
    else:
        print("Bad input, please use an integer")
        return False
    
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Background info
minVal=1
maxVal=100
goodGuesses=1
ANSWER=rd.randint( minVal, maxVal)
answerRight = 'Nope'


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Play the game
print( "Guess an integer such that", minVal, " <= X <= ", maxVal )

while answerRight == 'Nope':
    
    # Get the guess
    
    guess = input("\nEnter an integer: ")
    
    # Check to make sure the guess is an integer
    goodAns = guessChecker( guess )
    
    # Yes an integer
    if goodAns == True:
        guessInt = int( guess ) 
        
        # Check to see if guess is above the answer 
        if guessInt > ANSWER:
            print("Answer is too high, please guess again")
            maxVal = guessInt
            goodGuesses = goodGuesses+1
            print( "Your current inclusive range is ", minVal, " - ", maxVal )
        elif guessInt < ANSWER:
            print("Answer is too low, please guess again")
            minVal = guessInt
            goodGuesses = goodGuesses+1
            print( "Your current inclusive range is ", minVal, " - ", maxVal )
        else:
            print("\nHurray, you guessed ", ANSWER, " in ", goodGuesses, " guesses! " )
            answerRight = 'Yep'
    
    # Not an integer
    else:
        print( "Please try again")    
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_21624/613209405.py[0m in [0;36m<module>[1;34m[0m
[0;32m     52[0m     [1;31m# Get the guess[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m     53[0m [1;33m[0m[0m
[1;32m---> 54[1;33m     [0mguess[0m [1;33m=[0m [0minput[0m[1;33m([0m[1;34m"\nEnter an integer: "[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     55[0m [1;33m[0m[0m
[0;32m     56[0m     [1;31m# Check to make sure the guess is an integer[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\wintest\lib\site-packages\ipykernel\kernelbase.py[0m in [0;36mraw_input[1;34m(self, prompt)[0m
[0;32m   1002[0m         [1;32mif[0m [1;32mnot[0m [0mself[0m[1;33m.[0m[0m_allow_stdin[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1003[0m             raise StdinNotImplementedError(
[1;32m-> 1004[1;33m                 [1;34m"raw_input was called, but this frontend does not support input requests."[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1005[0m             )
[0;32m   1006[0m         return self._input_request(

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

